---
- name: "Install postfix packages"
  package:
    name: ["postfix"]
    state: present

- name: "Install sasl packages (Debian Family)"
  package:
    name: ["sasl2-bin", "libsasl2-modules"]
    state: present
  when: ansible_os_family == "Debian"

- name: "Install sasl packages (RedHat Family)"
  package:
    name: ["cyrus-sasl", "cyrus-sasl-plain", "cyrus-sasl-lib"]
    state: present
  when: ansible_os_family == "RedHat"

- name: "Configure main.cf"
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0444
    backup: true
  notify: restart postfix

- name: "Configure mailutils.conf"
  template:
    src: mailutils.conf.j2
    dest: /etc/mailutils.conf
    owner: root
    group: root
    mode: 0444
    backup: true
  notify: restart postfix

- name: "Configure sasl_passwd"
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0400
    backup: true
  notify:
    - postmap sasl_passwd
    - reload postfix

- name: "Configure sasl module (Debian Family)"
  template:
    src: smtpd.conf.j2
    dest: /etc/postfix/sasl/smtpd.conf
    owner: root
    group: root
    mode: 0444
    backup: true
  notify: restart postfix
  when: ansible_os_family == "Debian"

- name: "Configure sasl module (RedHat Family)"
  template:
    src: smtpd.conf.j2
    dest: /etc/sasl2/smtpd.conf
    owner: root
    group: root
    mode: 0444
    backup: true
  notify: restart postfix
  when: ansible_os_family == "RedHat"

- name: "Configure relay user"
  command: saslpasswd2 -c -p -f {{ sasldb2_file }} {{ sasldb2_username | quote }}
  args:
    stdin: "{{ sasldb2_password }}"
  notify: restart postfix
  when: sasldb2_file is defined

- name: "Check sasldb2 credentials"
  file:
    path: "{{ sasldb2_file }}"
    mode: 0440
    owner: root
    group: postfix
  when: sasldb2_file is defined

- name: "Configure saslauthd"
  template:
    src: saslauthd.conf.j2
    dest: /etc/saslauthd.conf
    mode: 0440
    owner: root
    group: root
  notify: restart saslauthd
  when: saslauthd_enable

- name: "Enable saslauthd"
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "^START=.*$"
    line: "START=yes"
    backup: true
  notify: restart saslauthd
  when: saslauthd_enable and ansible_os_family != "RedHat"
  
- name: "Change saslauthd mechanism"
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "^MECHANISMS=.*$"
    line: "MECHANISMS=ldap"
    backup: true
  notify: restart saslauthd
  when: saslauthd_enable

- name: "Change saslauthd mechanism options"
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "^MECH_OPTIONS=.*$"
    line: 'MECH_OPTIONS="/etc/saslauthd.conf"'
    backup: true
  notify: restart saslauthd
  when: saslauthd_enable

- name: "Change saslauthd socket"
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "^(OPTIONS=.*)-m /var/run/saslauthd(.*)$"
    backrefs: true
    line: '\1-m /var/spool/postfix/var/run/saslauthd\2'
    backup: true
  notify: restart saslauthd
  when: saslauthd_enable

- name: "Check if saslauthd socket dir exists"
  stat:
    path: /var/spool/postfix/var/run/saslauthd
  register: saslauthddir

- name: "Create saslauthd socket dir"
  command: dpkg-statoverride --force-all --add root sasl 710 /var/spool/postfix/var/run/saslauthd
  args:
    creates: /var/spool/postfix/var/run/saslauthd
    warn: false
  when: not saslauthddir.stat.exists and saslauthd_enable

- name: "Add postfix to sasl group"
  user:
    name: postfix
    groups: sasl
    append: true
  notify: restart postfix

- name: rebuild newaliases
  command: newaliases
  args:
    warn: false
  changed_when: false
