---
- name: postmap sasl_passwd
  command: postmap /etc/postfix/sasl_passwd

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: restart saslauthd
  service:
    name: saslauthd
    state: restarted
